spring:
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  sql:
    init:
      mode: always
      data-locations: classpath:/test-data.sql

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

